name: Pruebas Cypress

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json
        working-directory: .  # Ejecútalo en la raíz del repositorio

      - name: Install dependencies
        run: npm install
        working-directory: .  # Ejecútalo en la raíz del repositorio

      - name: Start the application
        run: npm run dev &
        working-directory: .  # Ejecútalo en la raíz del repositorio
        env:
          CI: true

      - name: Wait for the application to be ready
        run: npx wait-on http://localhost:5173
        working-directory: .  # Ejecútalo en la raíz del repositorio

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: .  # Ejecútalo en la raíz del repositorio
